/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sraguram' at '27/07/15 17:05' with Gradle 2.5
 *
 * @author sraguram, @date 27/07/15 17:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
