import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sraguram' at '27/07/15 17:05' with Gradle 2.5
 *
 * @author sraguram, @date 27/07/15 17:05
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void shouldGetLibVersion() {
        Library lib = new Library();

        assertThat(lib.version(), is("2.2"));
    }
}
